<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Kkindle.Desktop.Linux</RootNamespace>
    <AssemblyName>Kkindle</AssemblyName>
    <Product>Kkindle</Product>
    <Authors>kingstacker</Authors>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kkindle.App\Kkindle.App.csproj" />
    <ProjectReference Include="..\Kkindle.Infrastructure\Kkindle.Infrastructure.csproj" />
    <ProjectReference Include="..\Kkindle.Platform.Linux\Kkindle.Platform.Linux.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
  </ItemGroup>
</Project>
