using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Kkindle.Core;
using Kkindle.Infrastructure;
using Kkindle.McpServer;
using Kkindle.Platform.Common;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ModelContextProtocol;
using ModelContextProtocol.Server;

// Structured-output schemas generated by the SDK mark nullable properties as
// required keys, so a null value must still be emitted as an explicit null
// (e.g. reading progress for an unread book, or an unspecified device id).
// The SDK default serializer omits nulls (WhenWritingNull), which makes strict
// MCP clients (mcp>=2 with output-schema validation) reject tool results with
// "missing required property". Derive from the SDK defaults and only change
// the ignore condition so enum/type-info wiring is preserved.
var mcpSerializerOptions = new JsonSerializerOptions(McpJsonUtilities.DefaultOptions)
{
    DefaultIgnoreCondition = JsonIgnoreCondition.Never,
};

var paths = new AppPaths(McpRootPath.Resolve(args));
var mcpSettings = LoadMcpSettings(paths);
var metadata = new BookMetadataService();
var library = new SqliteBookLibraryService(paths, metadata);
var readerData = new ReaderDataService(paths);
var devices = new MassStorageKindleDeviceService(paths, metadata);
var ejectDevices = McpPlatformServices.CreateEjectService(paths, metadata);
var formatConverter = new BookFormatConversionService();
var emailSettingsStore = new KindleEmailSettingsStore(paths, new McpSecretProtector());
var emailSender = new KindleEmailSender();
var mcpTools = new KkindleMcpTools(
    library,
    readerData,
    devices,
    formatConverter,
    emailSettingsStore,
    emailSender,
    ejectDevices);
var enabledTools = CreateEnabledTools(mcpTools, mcpSettings, mcpSerializerOptions);

var builder = Host.CreateApplicationBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddConsole(options =>
{
    // stdout is reserved for MCP JSON-RPC messages.
    options.LogToStandardErrorThreshold = LogLevel.Trace;
});

builder.Services.AddSingleton(paths);
builder.Services.AddSingleton<IBookLibraryService>(library);
builder.Services.AddSingleton(readerData);
builder.Services.AddSingleton<IKindleDeviceService>(devices);
builder.Services.AddSingleton<IBookFormatConverter>(formatConverter);
builder.Services.AddSingleton(emailSettingsStore);
builder.Services.AddSingleton(emailSender);
builder.Services.AddSingleton(mcpTools);
if (ejectDevices is not null)
    builder.Services.AddSingleton(ejectDevices);
builder.Services
    .AddMcpServer()
    .WithStdioServerTransport()
    // ModelContextProtocol supports registering a concrete tool collection, so
    // disabled settings are absent from both tools/list and tools/call.
    .WithTools(enabledTools);

using var host = builder.Build();
await host.Services.GetRequiredService<IBookLibraryService>().InitializeAsync();
await host.Services.GetRequiredService<ReaderDataService>().InitializeAsync();
await host.RunAsync();

static McpServerSettings LoadMcpSettings(AppPaths paths)
{
    try
    {
        paths.EnsureDirectories();
        using var stream = new FileStream(
            paths.Settings,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read | FileShare.Delete);
        var deserialized = JsonSerializer.Deserialize<AppSettings>(
            stream,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        if (deserialized?.McpServer is null)
            throw new JsonException("The app settings file does not contain MCP settings.");
        var settings = AppSettings.Normalize(deserialized);
        return McpServerSettings.Normalize(settings.McpServer);
    }
    catch (FileNotFoundException)
    {
        return McpServerSettings.Normalize(new AppSettings().McpServer);
    }
    catch (DirectoryNotFoundException)
    {
        return McpServerSettings.Normalize(new AppSettings().McpServer);
    }
    catch (Exception exception) when (exception is JsonException or IOException or UnauthorizedAccessException)
    {
        // A corrupt or unreadable configuration must fail closed. Enabling
        // destructive tools from model defaults would turn a settings error
        // into an authorization change.
        return new McpServerSettings
        {
            Enabled = false,
            BookLibraryEnabled = false,
            SearchBooksEnabled = false,
            BookMetadataEnabled = false,
            ReadingProgressEnabled = false,
            RecentBooksEnabled = false,
            TagsEnabled = false,
            CollectionsEnabled = false,
            BookFileEnabled = false,
            DeviceListEnabled = false,
            DeviceStatusEnabled = false,
            DeviceLibraryEnabled = false,
            EjectDeviceEnabled = false,
            SendToKindleEnabled = false,
            ConvertBookEnabled = false,
            ImportBookEnabled = false,
            DeleteBookEnabled = false,
            DeleteDeviceBookEnabled = false,
            CollectionManageEnabled = false,
            SearchBookContentEnabled = false,
            AnnotationsEnabled = false,
            BookmarksEnabled = false,
            ReadingDashboardEnabled = false
        };
    }
}

static IReadOnlyList<McpServerTool> CreateEnabledTools(
    KkindleMcpTools target,
    McpServerSettings settings,
    JsonSerializerOptions serializerOptions)
{
    if (!settings.Enabled)
        return [];

    var registrations = new (bool Enabled, string MethodName)[]
    {
        (settings.BookLibraryEnabled, nameof(KkindleMcpTools.ListLibraryAsync)),
        (settings.SearchBooksEnabled, nameof(KkindleMcpTools.SearchBooksAsync)),
        (settings.BookMetadataEnabled, nameof(KkindleMcpTools.GetBookMetadataAsync)),
        (settings.ReadingProgressEnabled, nameof(KkindleMcpTools.GetReadingProgressAsync)),
        (settings.RecentBooksEnabled, nameof(KkindleMcpTools.ListRecentAsync)),
        (settings.TagsEnabled, nameof(KkindleMcpTools.ListTagsAsync)),
        (settings.CollectionsEnabled, nameof(KkindleMcpTools.ListCollectionsAsync)),
        (settings.BookFileEnabled, nameof(KkindleMcpTools.GetBookFileAsync)),
        (settings.DeviceListEnabled, nameof(KkindleMcpTools.ListDevicesAsync)),
        (settings.DeviceStatusEnabled, nameof(KkindleMcpTools.DeviceStatusAsync)),
        (settings.DeviceLibraryEnabled, nameof(KkindleMcpTools.ListDeviceLibraryAsync)),
        (settings.EjectDeviceEnabled, nameof(KkindleMcpTools.EjectDeviceAsync)),
        (settings.SendToKindleEnabled, nameof(KkindleMcpTools.SendToKindleAsync)),
        (settings.ConvertBookEnabled, nameof(KkindleMcpTools.ConvertBookAsync)),
        (settings.ImportBookEnabled, nameof(KkindleMcpTools.ImportBookAsync)),
        (settings.DeleteBookEnabled, nameof(KkindleMcpTools.DeleteBookAsync)),
        (settings.DeleteDeviceBookEnabled, nameof(KkindleMcpTools.DeleteDeviceBookAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.CreateCollectionAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.RenameCollectionAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.DeleteCollectionAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.ClearCollectionAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.MergeCollectionsAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.AddBookToCollectionAsync)),
        (settings.CollectionManageEnabled, nameof(KkindleMcpTools.RemoveBookFromCollectionAsync)),
        (settings.SearchBookContentEnabled, nameof(KkindleMcpTools.SearchBookContentAsync)),
        (settings.AnnotationsEnabled, nameof(KkindleMcpTools.ListBookAnnotationsAsync)),
        (settings.BookmarksEnabled, nameof(KkindleMcpTools.ListBookmarksAsync)),
        (settings.ReadingDashboardEnabled, nameof(KkindleMcpTools.GetReadingDashboardAsync))
    };

    return registrations
        .Where(registration => registration.Enabled)
        .Select(registration => CreateTool(target, registration.MethodName, serializerOptions))
        .ToArray();
}

static McpServerTool CreateTool(
    KkindleMcpTools target,
    string methodName,
    JsonSerializerOptions serializerOptions)
{
    var method = typeof(KkindleMcpTools).GetMethod(
        methodName,
        BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly);
    if (method is null)
        throw new InvalidOperationException($"MCP tool method '{methodName}' was not found.");

    return McpServerTool.Create(
        method,
        target,
        new McpServerToolCreateOptions
        {
            SerializerOptions = serializerOptions,
        });
}
