<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Kkindle.Platform.Common</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kkindle.Core\Kkindle.Core.csproj" />
    <ProjectReference Include="..\Kkindle.Infrastructure\Kkindle.Infrastructure.csproj" />
  </ItemGroup>
</Project>
